services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: videogames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
