[project]
name = "template-python-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastembed>=0.7.3",
    "langchain>=1.2.12",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.11",
    "langchain-postgres>=0.0.17",
    "langchain-qdrant>=1.1.0",
    "langgraph>=1.1.2",
    "pre-commit>=4.5.1",
    "psycopg>=3.3.3",
    "qdrant-client>=1.15.1",
    "sentence-transformers>=5.3.0",
]
